use std::env;
use std::fs::File;
use std::io::*;

use graphix_lib::graphql_api::api_schema_builder;

fn main() -> std::io::Result<()> {
    let path = env::current_dir()?.join("api_schema.graphql");
    let mut f = File::create(&path)?;

    f.write_all(b"# AUTOGENERATED. DO NOT MODIFY. ALL CHANGES WILL BE LOST.\n\n")?;
    f.write_all(api_schema_builder().finish().sdl().as_bytes())?;

    println!("Updated: {}", path.display());
    Ok(())
}
