query IndexingStatuses {
  indexingStatuses {
    subgraph
    chains {
      __typename
      network
      ... on EthereumIndexingStatus {
        latestBlock {
          number
          hash
        }
        earliestBlock {
          number
        }
      }
    }
  }
}
