query ProofsOfIndexing($requests: [PublicProofOfIndexingRequest!]!) {
  publicProofsOfIndexing(requests: $requests) {
    deployment
    block {
      number
      hash
    }
    proofOfIndexing
  }
}
